#ifndef PINASSIGNMENT_H
#define PINASSIGNMENT_H

#define MAINLIGHT_PIN 6
#define MAINLIGHTBUTTON_PIN 4

#define TRUNK_LID_LIGHT_PIN 5
#define TRUNK_LID_LIGHT_BUTTON_PIN 7

#define WAKEUP_PIN 2

#endif